[build]
  publish    = "sparkflow-ui/dist"
  functions  = "netlify/functions"
  command    = "npm install --prefix sparkflow-ui && npm run build --prefix sparkflow-ui"

[dev]
  port       = 8888
  functions  = "netlify/functions"
  publish    = "sparkflow-ui/dist"

[functions]
  node_bundler = "esbuild"

# On désactive tout parsing auto du body pour Stripe signature
[functions."stripe-webhook"]
  parse = false
  external_node_modules = ["stripe", "@supabase/supabase-js"]
